#数据库、Redis、RabbitMQ
#开放端口:15672/5672
####启动 rabbitmq-plugins enable rabbitmq_management thymeleaf
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username : root
    password : 123
    driverClassName : com.mysql.jdbc.Driver
    max-active : 20
    max-idle : 8
    min-idle : 8
    initial-size : 10
    hikari:
          max-lifetime: 1765000
          maximum-pool-size: 10

  redis:
    database : 0
    host : 47.93.196.193
    port : 6379
    password :
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  application:
    name: spirng-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.163.com
    username: hao_jixiang@163.com
    password: hjx@969190
    default-encoding: UTF-8
  thymeleaf:
    cache: false


#发送者
mail:
  fromMail:
    addr: hao_jixiangg@163.com

# MyBatis
mybatis:
  type-aliases-package: com.ralap.bean
  configuration.map-underscore-to-camel-case: true

#log4j2
logging:
  file: log.log
  level:
    top.itfan.*.*: debug




